// AugularReact_projects/React-employee/src/App.js
/************************************************************************ *********
* WEB422 – Assignment 04
* I declare that this assignment is my own work in accordance with Seneca Academic Policy. No part of this
* assignment has been copied manually or electronically from any other source (including web sites) or
* distributed to other students. *
* Name: ___________cuifengzhi___________ Student ID: ___142045160___________ Date: ____7.6____________
* ********************************************************************************/



import React, { Component } from 'react';
import { Route, Switch } from 'react-router-dom' ;
import Overview from './Overview';
import Projects from './Projects'; 
import Teams from './Teams'; 
import Employees from './Employees'; 
import NotFound from './NotFound'; 
class App extends Component {
  render() {
    return (
      <Switch>
        <Route exact path='/' render={() => (
                <Overview />

        )}/>

        <Route exact path='/projects' render={() => (
                <Projects  />
        )}/>
         <Route exact path='/teams' render={() => (
                <Teams  />
        )}/>
        <Route exact path='/employees' render={() => (
            <Employees  />
        )}/>
         <Route render={() => (
            <NotFound />
        )}/>
    </Switch>
    );
  }
}

export default App;

// AugularReact_projects/Angular_employee/src/app/app.component.ts

/************************************************************************ *********
* WEB422 – Assignment 05
* I declare that this assignment is my own work in accordance with Seneca Academic Policy. No part of this
* assignment has been copied manually or electronically from any other source (including web sites) or
* distributed to other students. *
* Name: __________Fengzhi Cui____________ Student ID: _____142045160_________ Date: ____7/20____________
* ********************************************************************************/



import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
}
